[package]
name = "rusty_ai_gym"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.3.1"
ndarray = "0.15.6"

